services:

  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: store
#      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8'

    ports:
      - 5433:5432