[tool.poetry]
name = "py-hub-sore2"
version = "0.1.0"
description = ""
authors = ["k.barylnikov <ipt_git_bot@ipt.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
